backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/media
public_folder: /media
publish_mode: editorial_workflow
locale: "en"
search: false

collections:
  - name: 'books'
    label: 'წიგნები'
    folder: 'src/routes/books/'
    format: 'frontmatter'
    create: true
    slug: '{{fields.slug}}'
    editor:
      preview: false
    fields:
      - { label: 'სახელი', name: 'title', widget: 'string' }
      - { label: 'სტროფი', name: 'slug', widget: 'string' }
      - { label: 'გამოქვეყნების თარიღი', name: 'date', widget: 'datetime' }
      - { label: 'აღწერა', name: 'description', widget: 'string' }
        label: "კატეგორია",
        name: "category",
        widget: "select",
        multiple: true,
        options: [
          'წმინდა მამები',
          'თანამედროვე მოღვაწეები',
        ],
        default: ['თანამედროვე მოღვაწეები'],
        required: true
      }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "წიგნი"
        name: "ebook"
        widget: "file"
        required: false
        choose_url: true
        media_library:
          config:
            multiple: true
  