#!/usr/bin/env bash

SCRIPT_DIR="${0%/*}"
OUTPUT_DIR="$SCRIPT_DIR/../ourbible/bible-json"
DB_DIR="$SCRIPT_DIR/../database"

[ -d "$OUTPUT_DIR/book" ] || mkdir "$OUTPUT_DIR/book"

for db in "$DB_DIR/"*; do
  file="${db##*/}"
  module="${file%.SQLite3}"

  sqlite3 --json "$DB_DIR/$file" "SELECT * FROM books" \
    >"$OUTPUT_DIR/book/$module"
done
