#!/usr/bin/env bash

SCRIPT_DIR="${0%/*}"
OUTPUT_DIR="$SCRIPT_DIR/../ourbible/bible-json"
DB_DIR="$SCRIPT_DIR/../database"

OUTPUT_FILE="$OUTPUT_DIR/module"

output="["

commaPrintingEnabled=false
for db in "$DB_DIR/"*; do
  file="${db##*/}"
  [ "$commaPrintingEnabled" = true ] && output+=","
  module="${file%.SQLite3}"
  output+="$(sqlite3 --json "$DB_DIR/$file" \
    "SELECT * FROM info WHERE name != 'history_of_changes'" |
    jq 'map({(.name): .value}) | add' |
    sed "1s/{/{\"name\":\"$module\",/")"
  commaPrintingEnabled=true
done

output+="]"

echo $output >"$OUTPUT_FILE"
